algo_trading/algo_trading/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import RedirectView

urlpatterns = [

    url(r'algotrade/', include('website.urls')),
    url(r'^admin/', admin.site.urls),
    ]

algo_trading/website/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.views.generic.base import TemplateView
from . import views

app_name = 'website'
urlpatterns = [
    # ex: /polls/
    url(r'^$', views.homeView, name='home'),
    url(r'profileview/$', views.profileview, name='profileview'),
    url(r'profilesaveview/$', views.profilesaveview, name='profilesaveview'),
    url(r'scriptview/$', views.scriptview, name='scriptview'),
    url(r'scriptview/list/$', views.scriptListView, name='scriptListView'),
    url(r'scriptview/(?P<pk>\d+)/edit/$', views.scripteditview, name='scripteditview'),
    url(r'scripteditedview/$', views.scripteditedview, name='scripteditedview'),
    url(r'strategyview/(?P<pk>\d+)/edit/$', views.strategyeditview, name='strategyeditview'),
    url(r'strategyview/(?P<pk>\d+)/del/$', views.strategydelview, name='strategydelview'),
    url(r'strategyview/$', views.strategyview, name='startegyview'),
    url(r'strategyListView/$', views.strategyListView, name='strategyListView'),
    url(r'strategyaddview/$', views.strategyaddview, name='strategyaddview'),
    url(r'tradingview/$', views.tradingview, name='tradingview'),
    url(r'tradingview/list/$', views.tradingListView, name='tradingListView'),
    url(r'login/$', views.login, name='login'),
    url(r'logout/$', views.logout, name='logout'),
]

algo_trading/website/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class Trade(models.Model):
    trade_id = models.CharField(max_length=1, blank=False, null=False, primary_key = True)
    trade_value = models.CharField(max_length=1, blank=False, null=False)

    class Meta:
        managed = True
        db_table = 'trading_type'

class Target(models.Model):
    target_id = models.CharField(max_length=5, blank=False, null=False, primary_key = True)
    target_desc = models.CharField(max_length=20, blank=False, null=False)

    class Meta:
        managed = True
        db_table = 'target'

class Stoploss(models.Model):
    stoploss_id = models.CharField(max_length=5, blank=False, null=False, primary_key = True)
    stoploss_desc = models.CharField(max_length=20, blank=False, null=False)

    class Meta:
        managed = True
        db_table = 'stoploss'

class TimeFrame(models.Model):
    timeframe_id = models.AutoField(primary_key=True)
    timeframe_value = models.IntegerField(blank=False, null=False)

    class Meta:
        managed = True
        db_table = 'time_frame'

class UserRole(models.Model):
    role_id = models.BigIntegerField(blank=False, null=False, primary_key = True)
    user_id = models.CharField(max_length=6, blank=False, null=False)
    role_name = models.CharField(max_length=6, blank=False, null=False)
    description = models.CharField(max_length=20, blank=False, null=False)
    class Meta:
        managed = True
        db_table = 'user_role'

class UserProfile(models.Model):
    userprofile_id = models.AutoField(primary_key = True)
    user_id = models.CharField(max_length=6, blank=False, null=False)
    user_name = models.CharField(max_length=25, blank=False, null=False)
    secret_key = models.CharField(max_length=50, blank=False, null=False)
    api_key = models.CharField(max_length=50, blank=False, null=False)
    redirect_url = models.CharField(max_length=50, blank=False, null=False)
    access_token = models.CharField(max_length=50, blank=True, null=True)
    trade_type = models.CharField(max_length=1, blank=True, null=True)
    available_margin = models.FloatField(blank=True, null=True)
    is_today = models.BooleanField(blank=False, null=False, default=True)
    class Meta:
        managed = True
        db_table = 'Userprofile'

class Strategy(models.Model):
    strategy_id = models.AutoField(primary_key=True)
    strategy_name = models.CharField(max_length=20, blank=False, null=False)
    time_frame = models.IntegerField(blank=True, null=True)
    candle_ref = models.IntegerField(blank=True, null=True)
    no_of_candle = models.IntegerField(blank=True, null=True)
    buffer_amnt = models.FloatField(blank=False, null=False)
    chk_next_candle = models.BooleanField(blank=False, null=False, default=False)
    is_open_price = models.BooleanField(blank=False, null=False, default=False)
    combine_candle = models.BooleanField(blank=False, null=False, default=False)
    reverse_trade = models.BooleanField(blank=False, null=False, default=False)
    candle_high = models.FloatField(blank=True, null=True)
    candle_low = models.FloatField(blank=True, null=True)
    candle_close = models.FloatField(blank=True, null=True)
    candle_open = models.FloatField(blank=True, null=True)
    target_id = models.CharField(max_length=5, blank=True, null=True)
    stoploss_id = models.CharField(max_length=5, blank=True, null=True)
    condition1 = models.CharField(max_length=50, blank=True, null=True)
    condition2 = models.CharField(max_length=50, blank=True, null=True)
    condition3 = models.CharField(max_length=50, blank=True, null=True)

    def __unicode__(self):
        return u"%s" % self.name
    class Meta:
        managed = True
        db_table = 'strategy'

class Scripts(models.Model):
    script_id = models.AutoField(primary_key=True)
    script_name = models.CharField(max_length=50, blank=False, null=False)
    strategy = models.OneToOneField(Strategy, on_delete=models.CASCADE)
    trade = models.OneToOneField(Trade, on_delete=models.CASCADE)
    exchange_type = models.CharField(max_length=10, blank=True, null=True)
    is_strategy_active = models.BooleanField(blank=False, null=False, default=True)

    class Meta:
        managed = True
        db_table = 'scripts'

class Trading(models.Model):
    trading_id = models.AutoField(primary_key=True)
    script = models.OneToOneField(Scripts, on_delete=models.CASCADE)
    trade = models.OneToOneField(Trade, on_delete=models.CASCADE)

    class Meta:
        managed = True
        db_table = 'trading'

algo_trading/website/forms.py
from django import forms
from .models import *

class LoginForm(forms.Form):
     username = forms.CharField(max_length=6,required=True)
     password = forms.CharField(required=True)
     birthyear = forms.IntegerField(required=True)

class ProfileForm(forms.Form):
     selAvailableMargin = forms.FloatField(required=True)
     selTradeType = forms.CharField(max_length=1, required=False)

class StrategyForm(forms.Form):
     selStrategyName = forms.IntegerField(required=False)
     selTimeFrame = forms.IntegerField(required=False)

class ScriptForm(forms.Form):
    selTradeType = forms.CharField(max_length=1, required=False)
    selStrategyName = forms.IntegerField(required=False)
    selScriptName = forms.CharField(max_length=20, required=False)

class TradingForm(forms.Form):
    selTradeType = forms.CharField(max_length=1, required=False)
    selScriptName = forms.CharField(max_length=20, required=False)

class AddStrategyForm(forms.ModelForm):
    ops = forms.CharField(max_length=4, required=False)
    st_id = forms.IntegerField(required=False)
    class Meta:
        model = Strategy
        fields = '__all__'

class AddScriptForm(forms.Form):
    ops = forms.CharField(max_length=4, required=False)
    st_id = forms.IntegerField(required=False)
    selTradeType = forms.CharField(max_length=1, required=True)
    selStrategyName = forms.IntegerField(required=True)
    exchange_type = forms.CharField(max_length=10, required=False)
    is_strategy_active = forms.BooleanField(required=False)
    script_name = forms.CharField(max_length=20, required=False)

algo_trading/website/views.py
# Create your views here.
from django.shortcuts import render, redirect
from django.shortcuts import HttpResponse
from django.core.exceptions import *
from _ast import *
from django.db.models.sql.where import OR
from .models import *
from .forms import *
from init_python import *
import json
from utils import *
from pprint import pprint

@validation(login_validator, if_invalid='ADMIN')
def scriptview(request):
    if request.method == 'POST' :
        form = ScriptForm(request.POST)
        context = {"scriptList":getScripts, "form":form,"scriptList":getScripts, "scripts": getScripts, "startegies":getStrategies, "trades": getTradeTypes, "title": "",'username': request.session['username'], 'is_authenticated': True,'pageTitle':'Script of the day'}

    else:
        form = ScriptForm()
        context = {"scriptList":getScripts, "form":form,  "timeFrames":getTimeFrmaes, "scripts": getScripts, "startegies":getStrategies, "trades": getTradeTypes, "title": "",'username': request.session['username'], 'is_authenticated': True,'pageTitle':'Script of the day'}
    return render(request, 'scripts.html', context)

@validation(login_validator, if_invalid='ADMIN')
def scriptListView(request):
    if request.method == 'POST' :
        form = ScriptForm(request.POST)
        if form.is_valid() :
            st_id = request.POST.get('selStrategyName')
            tr_id = form.cleaned_data['selTradeType']
            sc_id = form.cleaned_data['selScriptName']
            hid_sc_id = request.POST.get('hid_script_id', None)
            operation = request.POST.get('operation', None)
            print(hid_sc_id, operation)
            if operation != None and operation == "del":
                print ("Del ops")
                deleteScript(hid_sc_id)
            elif operation != None and operation == "edit":
                print ("Eidt ops")
                sc = getScript(hid_sc_id)
                form = AddScriptForm(instance=sc)
                context = {"form":form, "scripts": getScripts,  "startegies":getStrategies, "trades": getTradeTypes, "title": "",'username': request.session['username'], 'is_authenticated': True,'pageTitle':'Script of the day'}
                return render(request, 'scriptEdit.html', context)
            else :
                errorMsg = saveScripts(st_id, tr_id, sc_id)
                stList = getScripts()
                context = {"is_error":True,'errorMsg':errorMsg,"form":form,"scripts": getScripts, "scriptList":stList, "startegies":getStrategies, "trades": getTradeTypes, "title": "",'username': request.session['username'], 'is_authenticated': True,'pageTitle':'Script of the day'}

        else:
            form = ScriptForm()
            context = {"form":form, "scripts": getScripts,  "startegies":getStrategies, "trades": getTradeTypes, "title": "",'username': request.session['username'], 'is_authenticated': True,'pageTitle':'Script of the day'}
        return render(request, 'scripts.html', context)

@validation(login_validator, if_invalid='ADMIN')
def scripteditview(request, pk):
    print("edit view")
    if request.method == 'POST' :
        print("in POST")
        form = AddScriptForm(request.POST)
        if form.is_valid() :
            pk = form.cleaned_data['st_id']
            script_modal = form.save(commit=False)
            script_modal.script_id = pk
            script_modal.save()
        return redirect('/algotrade/scriptview/',request)
    else:
        sc_modal = getScript(pk)
        print(sc_modal.script_id)
        form = AddScriptForm()
        form.fields['st_id'].initial = pk
        form.fields['script_name'].initial = sc_modal.script_name
        form.fields['selTradeType'].initial = sc_modal.trade.trade_id
        form.fields['selStrategyName'].initial = sc_modal.strategy.strategy_id
        form.fields['exchange_type'].initial = sc_modal.exchange_type
        form.fields['is_strategy_active'].initial = sc_modal.is_strategy_active
        print(sc_modal.is_strategy_active)
        context = {"form":form, "scripts": getScripts,  "startegies":getStrategies, "trades": getTradeTypes, "title": "",'username': request.session['username'], 'is_authenticated': True,'pageTitle':'Script of the day'}
    return render(request, 'scriptEdit.html', context)

@validation(login_validator, if_invalid='ADMIN')
def strategyview(request):
    print("view")
    if request.method == 'POST' :
        print("POST")
        form = StrategyForm(request.POST)
        context = {"form":form, "stList":getStrategies,"timeFrames":getTimeFrmaes,"scripts": getScripts, "startegies":getStrategies, "trades": getTradeTypes, "title": "",'username': request.session['username'], 'is_authenticated': True,'pageTitle':'Script of the day'}
    else:
        print("normal")
        form = StrategyForm()
        context = {"form":form, "stList":getStrategies,"timeFrames":getTimeFrmaes, "scripts": getScripts, "startegies":getStrategies, "trades": getTradeTypes, "title": "",'username': request.session['username'], 'is_authenticated': True,'pageTitle':'Script of the day'}
    return render(request, 'strategy.html', context)

@validation(login_validator, if_invalid='ADMIN')
def scripteditedview(request):
    print("edited view")
    if request.method == 'POST' :
        print("in POST")
        ops = request.POST.get("ops")
        form = AddScriptForm(request.POST)
        if form.is_valid() :
            sc_id = request.POST.get("st_id")
            st_id = request.POST.get('selStrategyName')
            tr_id = request.POST.get('selTradeType')
            sc_name=request.POST.get('script_name')
            ex_type=request.POST.get('exchange_type')
            is_active= form.cleaned_data['is_strategy_active']
            script_modal = getScript(sc_id)
            if(ops == 'Edit'):
                script_modal.script_name = sc_name
                script_modal.exchange_type = ex_type
                script_modal.is_strategy_active = is_active
                print(is_active)
                script_modal.strategy = Strategy.objects.get(strategy_id=st_id)
                script_modal.trade = Trade.objects.get(trade_id=tr_id)
                script_modal.save()
            else :
                script_modal.delete()
        return redirect('/algotrade/scriptview/',request)
    else:
        sc_modal = getScript(pk)
        form = AddScriptForm(instance=sc_modal)
        form.fields['st_id'].initial = pk
        context = {"form":form, "scripts": getScripts,  "startegies":getStrategies, "trades": getTradeTypes, "title": "",'username': request.session['username'], 'is_authenticated': True,'pageTitle':'Script of the day'}
    return render(request, 'scriptEdit.html', context)

@validation(login_validator, if_invalid='ADMIN')
def strategyaddview(request):
    print("add view")
    if request.method == 'POST' :
        print("in POST")
        form = AddStrategyForm(request.POST)
        if form.is_valid() :
            ops= form.cleaned_data['ops']
            st_id = form.cleaned_data['st_id']
            if ops == 'Add':
                strategy_modal = form.save()
            elif ops== 'Edit' :

                strategy_modal = form.save(commit=False)
                strategy_modal.strategy_id = st_id
                strategy_modal.save()
            elif ops == 'Del':
                strategy_modal = getStrategy(st_id)
                strategy_modal.delete()
            return redirect('/algotrade/strategyview/',request)
    else:
        form = AddStrategyForm()
        context = {"form":form, "timeFrames":getTimeFrmaes, "targets": getTargets, "stoploss":getStoploss, "trades": getTradeTypes, "title": "",'username': request.session['username'], 'is_authenticated': True,'pageTitle':'Script of the day'}
    return render(request, 'strategyAdd.html', context)

@validation(login_validator, if_invalid='ADMIN')
def strategyeditview(request, pk):
    print("edit view")
    if request.method == 'POST' :
        print("in POST")
        form = AddStrategyForm(request.POST)
        if form.is_valid() :
            strategy_modal = form.update()
            return redirect('/algotrade/strategyview/',request)
    else:
        st= getStrategy(pk)
        print(st.strategy_id)
        form = AddStrategyForm(instance=st)
        form.fields['st_id'].initial = st.strategy_id

        context = {"form":form, "editOps":True,"timeFrames":getTimeFrmaes, "targets": getTargets, "stoploss":getStoploss, "trades": getTradeTypes, "title": "",'username': request.session['username'], 'is_authenticated': True,'pageTitle':'Script of the day'}
    return render(request, 'strategyAdd.html', context)

@validation(login_validator, if_invalid='ADMIN')
def strategydelview(request, pk):
    print("del view")
    if request.method == 'POST' :
        print("in POST")
        form = AddStrategyForm(request.POST)
        if form.is_valid() :
            strategy_modal = form.update()
            return redirect('/algotrade/strategyview/',request)
    else:
        st= getStrategy(pk)
        print(st.strategy_id)
        st.delete()
    return redirect('/algotrade/strategyview/',request)

@validation(login_validator, if_invalid='ADMIN')
def strategyListView(request):
    if request.method == 'POST' :
        form = StrategyForm(request.POST)
        if form.is_valid() :
            st_id = form.cleaned_data['selStrategyName']
            tf = form.cleaned_data['selTimeFrame']
            stList = getStrategyList(st_id, tf);
        context = {"form":form,"stList":stList,"timeFrames":getTimeFrmaes,"scripts": getScripts, "startegies":getStrategies, "trades": getTradeTypes, "title": "",'username': request.session['username'], 'is_authenticated': True,'pageTitle':'Script of the day'}
    else:
        form = StrategyForm()

algo_trading/website/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
   <title>Upstox ALGO Trading</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
  <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" />
	<link rel="stylesheet" href="{% static "css/upstox.css" %}" />
<script src="{% static "js/jquery.min.js" %}"></script>
<script src="{% static "js/upstox.js" %}"></script>
  <script src="{% static "js/bootstrap.min.js" %}"></script>
   <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <nav class="navbar navbar-default">
      <div class="container">
     	<div class="navbar-header">
        <a class="navbar-brand" href="#">Upstox ALGO Trading</a>
            {% if is_authenticated %}
            </div>
      <div class="nav pull-right">
      <strong>Hi {{ username }}!
      <button type="button" class="btn navbar-btn"><a href="{% url 'website:logout' %}">Logout</a></button>
      </div>
    {% endif %}
      </div>
    </nav>
    </nav>
  </header>
<body>
 	<div class="container">
	{% if is_error %}
         <strong style="color:red"> *{{ errorMsg }}</strong>
    {%endif %}
    </div>
  <main>
    {% block content %}

    {% endblock %}
  </main>
  <hr>
  <footer class="py-1 bg-light fixed-bottom">
      <div class="container">
        <p class="m-0 text-center text-black">Copyright &copy; Your Website 2018</p>
      </div>
      <!-- /.container -->
    </footer>

  </body>

</html>

algo_trading/website/templates/home.html
{% extends 'base.html' %}

{% block content %}
	<div class="container">
	 <h4 class="my-4">Home</h4>
		<div class="row">
			<div class="col-lg-4">
				<div class="panel panel-default">
					<div class="panel-heading">ALGO Trading</div>
					<div class="panel-body">Lorem ipsum dolor sit amet,
						consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
						labore et dolore magna aliqua. Ut enim ad minim veniam, quis
						nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
						consequat. Duis aute irure dolor in reprehenderit in voluptate
						velit esse cillum dolore eu fugiat nulla pariatur</div>
					<div class="panel-body">
						<button type="submit" class="btn btn-default">Learn more</button>
					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="panel panel-default">
				<div class="panel-heading">Login</div>
					<div class="panel-body">
						<form action="login/" method="POST">
						{% csrf_token %}
										<div class="form-group">
										<input type="text" class="form-control" value="{{ form.username.value|default:""}}" placeholder="username" name="{{ form.username.name}}">
										</div>
										<div class="form-group">
											<input type="password" class="form-control" value="{{ form.password.value|default:""}}" placeholder="password" name="{{ form.password.name}}">
										</div>
										<div class="form-group">
											<input type="text" class="form-control" value="{{form.birthyear.value|default:""}}" placeholder="birthyear" name="{{form.birthyear.name}}">
										</div>
						        <input type="submit" value="Log in" class="btn btn-primary" style="width:100px">
									    <br>

					</div>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="panel panel-default">
					<div class="panel-heading">ALGO Trading Advantages</div>
					<div class="panel-body">Lorem ipsum dolor sit amet,
						consectetur adipiscing elit, sed do eiusmod tempor incididunt ut
						labore et dolore magna aliqua. Ut enim ad minim veniam, quis
						nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
						consequat. Duis aute irure dolor in reprehenderit in voluptate
						velit esse cillum dolore eu fugiat nulla pariatur</div>
					<div class="panel-body">
						<button type="submit" class="btn btn-default">Learn more</button>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

algo_trading/website/templates/logged_out.html
{% extends 'base.html' %}

{% block title %}See you!{% endblock %}

{% block content %}
  <h2>Logged out</h2>
  <p>You have been successfully logged out.</p>
  <p><a href="{% url 'login' %}">Log in</a> again.</p>
{% endblock %}

algo_trading/website/templates/scripts.html
{% extends 'base.html' %}

{% block content %}
	<div class="container">
	 <h4 class="my-4">Scripts of the day</h4>
		<div class="row">
			<div class="col-lg-2">
				<div class="row">
					<div class="col-lg-12">
						<div class="well well-sm"><a href="/algotrade/scriptview">Scripts for Today</a></div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12">
						<div class="well well-sm"><a href="/algotrade/strategyview">Strategy</a></div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12">
						<div class="well well-sm"><a href="/algotrade/tradingview">Trading</a></div>
					</div>
				</div>
			</div>

			<!-- Panel body -->

			<div class="col-lg-7">
				<div class="panel panel-default">
					<div class="panel-body">
						<div class="container-fluid">
							<div class="row" style="font-weight:normal">
								<form action="/algotrade/scriptview/list/" method="POST" name="scForm" id="scForm">
									{% csrf_token %}
								<div class="col-lg-4">
									<div class="form-group">
											<select class="form-control" name="{{form.selScriptName.name}}" title="Script Name..">
												{% with value=form.selScriptName.value %}
											<option value="0" selected> Script Name..</option>
										{% for script in scripts %}
												<option value="{{ script.script_id }}" {% if script.script_id|slugify == value|slugify %}selected="selected"{% endif %}>{{ script.script_name }}</option>
										{% endfor %}
										{% endwith%}
										</select>
									</div>
								</div>
								<!-- end -->
								<div class="col-lg-4">
									<div class="form-group">
											<select class="form-control" name="{{form.selStrategyName.name}}" title="Strategy Name..">
												{% with value=form.selStrategyName.value %}
											<option value="0" selected> Strategy Name..</option>
										{% for startegy in startegies %}
												<option value="{{ startegy.strategy_id }}" {% if startegy.strategy_id|slugify == value|slugify %}selected="selected"{% endif %}>{{ startegy.strategy_name }}</option>
										{% endfor %}
										{% endwith%}
										</select>
									</div>
								</div>
								<div class="col-lg-4">
									<div class="form-group">
											<select class="form-control" name="{{form.selTradeType.name}}" title="Trade Type ..">
													{% with value=form.selTradeType.value %}
											<option value="0" selected> Trade Type.. </option>
										{% for trade in trades %}
												<option value="{{ trade.trade_id }}" {% if trade.trade_id|slugify == value|slugify %}selected="selected"{% endif %}>{{ trade.trade_value }}</option>
										{% endfor %}
											{% endwith%}
										</select>
									</div>
								</div>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-4"></div>
							<div class="col-lg-4">
								<button type="submit" class="btn btn-primary" style="width:100px" onclick="/algotrade/">Save</button>
							</div>
							<input type="hidden" name="hid_script_id" value="" />
							<input type="hidden" name="operation" value="">
						</form>
						<div class="col-lg-4"></div>
						</div>
						<br>
						<div class="row">

							<div class="col-lg-12">
								<table class="table table-striped">
									<thead>
										<tr>
											<th>Sl No</th>
											<th>Script Name</th>
											<th>Strategy</th>
											<th>Trade Type</th>
										</tr>
									</thead>
									<tbody style="font-weight:normal">
										{% for script in scriptList %}

										<tr >
											<td>{{forloop.counter}}</td>
											<td>{{script.script_name}}</td>
											<td>{{script.strategy.strategy_name}}</td>
											<td>{{script.trade.trade_value}}</td>
											<td><button type="button" href="{% url 'website:scripteditview' script.script_id %}"
													class="btn btn-block btn-primary" style="float:right;width:100px" data-toggle="modal"
            								data-target="#myModal1">Edit/Del</button>
												</td>
										</tr>
										{% endfor %}

									</tbody>
								</table>
							</div>
						</div>
						<!-- lastrow -->

					</div>
				</div>
			</div>
		</div>
</div>
<div id="myModal1" class="modal fade" role="dialog">
		 <div class="modal-dialog">
			 <div class="modal-content">
					 <!-- Content will be loaded here from "remote.php" file -->
			 </div>
		 </div>
</div>
</div>
{% endblock %}

algo_trading/website/templates/strategy.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
 <h4 class="my-4">Strategy</h4>
  <div class="row">
    <div class="col-lg-2">
      <div class="row">
        <div class="col-lg-12">
          <div class="well well-sm"><a href="/algotrade/scriptview">Scripts for Today</a></div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <div class="well well-sm"><a href="/algotrade/strategyview">Strategy</a></div>
        </div>
      </div>
      <div class="row">
        <div class="col-lg-12">
          <div class="well well-sm"><a href="/algotrade/tradingview">Trading</a></div>
        </div>
      </div>
    </div>

			<!-- Panel body -->

			<div class="col-lg-7">
				<div class="panel panel-default">
					<div class="panel-body">
						<div class="container-fluid">
							<div class="row" style="font-weight:normal">
                <form action="/algotrade/strategyListView/" method="POST">
                  {% csrf_token %}
                <div class="col-lg-4">
                  <div class="form-group">
                      <select class="form-control" name="{{form.selStrategyName.name}}" title="Strategy Name..">
                        {% with value=form.selStrategyName.value %}
                        <option value="0" selected> Strategy Name..</option>
                    {% for startegy in startegies %}
                        <option value="{{ startegy.strategy_id }}"  {% if startegy.strategy_id|slugify == value|slugify %}selected="selected"{% endif %}>{{ startegy.strategy_name }}</option>
                    {% endfor %}
                    </select>
                      {% endwith %}
                  </div>
                </div>
								<!-- end -->
                <div class="col-lg-4">
                  <div class="form-group">
                      <select class="form-control" name="selTimeFrame" title="Strategy Name..">
                          {% with value=form.selTimeFrame.value %}
                      <option value="0" selected> Time Frame..</option>
                    {% for timeframe in timeFrames %}
                        <option value="{{ timeframe.timeframe_value }}"  {% if timeframe.timeframe_value|slugify == value|slugify %}selected="selected"{% endif %}>{{ timeframe.timeframe_value }}</option>
                    {% endfor %}
                    </select>
                      {% endwith %}
                  </div>
                </div>
								<div class="col-lg-4">
									<button type="submit" class="btn btn-block btn-primary" style="float:right;width:100px">Filter</button>
								</div>
              </form>
							</div>
						</div>
						<div class="row">
							<div class="col-lg-12">
								<table class="table table-striped">
									<thead>
										<tr>
											<th>Strategy Name</th>
											<th>Time Frame</th>
											<th>Buffer Amount</th>
											<th>Action</th>
										</tr>
									</thead>
									<tbody>
                    {% for st in stList %}
										<tr style="font-weight:normal">
											<td>{{st.strategy_name}}</td>
											<td>{{st.time_frame}}</td>
											<td>{{st.buffer_amnt}}</td>
											<td><button type="button" href="{% url 'website:strategyeditview' st.strategy_id %}"
													class="btn btn-block btn-primary" style="float:right;width:100px" data-toggle="modal"
            								data-target="#myModal">Edit/Delete</button></td>
										</tr>
                    {% endfor %}
									</tbody>
								</table>
							</div>
						</div>
						<!-- lastrow -->
						<div class="text-center">
							<button href="/algotrade/strategyaddview" type="button" class="btn btn-primary" style="width:100px" data-toggle="modal"
								data-target="#myModal">Add</button>
						</div>
					</div>
				</div>
			</div>
		</div>

		  <div id="myModal" class="modal fade" role="dialog">
			     <div class="modal-dialog modal-lg">
             <div class="modal-content">
                 <!-- Content will be loaded here from "remote.php" file -->
             </div>
				   </div>
      </div>
		</div>

{% endblock %}